package com.clearpath.export

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import androidx.core.content.FileProvider
import com.clearpath.data.route.SavedRoute
import java.io.File

/**
 * Renders a route debrief summary as a bitmap and shares it.
 * Strips all metadata (no EXIF, no GPS tags).
 */
object DebriefImageExporter {

    fun shareDebriefImage(context: Context, route: SavedRoute) {
        val bitmap = renderDebriefBitmap(route)
        val file   = saveBitmap(context, bitmap)
        val uri    = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)

        val intent = Intent(Intent.ACTION_SEND).apply {
            type    = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share journey debrief"))
    }

    private fun renderDebriefBitmap(route: SavedRoute): Bitmap {
        val width  = 800
        val height = 480
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        // Background
        canvas.drawColor(Color.parseColor("#0D1117"))

        val headerPaint = Paint().apply {
            color    = Color.parseColor("#F59E0B")
            textSize = 32f
            typeface = Typeface.MONOSPACE
        }
        val bodyPaint = Paint().apply {
            color    = Color.parseColor("#E6EDF3")
            textSize = 22f
            typeface = Typeface.MONOSPACE
        }
        val mutedPaint = Paint().apply {
            color    = Color.parseColor("#8B949E")
            textSize = 18f
            typeface = Typeface.MONOSPACE
        }

        canvas.drawText("ClearPath — Journey Debrief", 40f, 60f, headerPaint)
        canvas.drawText(route.name, 40f, 100f, mutedPaint)

        canvas.drawText("Exposure score: %.0f / 100".format(route.exposureScore), 40f, 150f, bodyPaint)
        canvas.drawText("Distance: ${route.distanceMetres}m", 40f, 185f, bodyPaint)
        canvas.drawText("Cameras encountered: ${route.cameraCount}", 40f, 220f, bodyPaint)
        val totalSecs = route.cameraEncounters.sumOf { it.estimatedExposureSeconds }
        canvas.drawText("Time in coverage: ${totalSecs}s", 40f, 255f, bodyPaint)

        canvas.drawText("Generated by ClearPath (no metadata)", 40f, height - 30f, mutedPaint)

        return bitmap
    }

    private fun saveBitmap(context: Context, bitmap: Bitmap): File {
        val dir  = File(context.cacheDir, "exports").also { it.mkdirs() }
        val file = File(dir, "debrief_${System.currentTimeMillis()}.png")
        file.outputStream().use { out ->
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
        }
        bitmap.recycle()
        return file
    }
}
